using System.Collections.Generic;
using UnityEngine;

// Sound effects. Clips live in Assets/Resources/Audio (generated by Tools/generate_sfx.py) and are loaded
// on first use; a hidden, persistent object owns the AudioSource so nothing has to be wired in a scene.
// Master volume is PlayerData.masterVolume (0..1) applied via AudioListener.volume, so it also covers
// anything added later.
public class GameAudio : MonoBehaviour
{
    private static GameAudio instance;
    private static readonly Dictionary<string, AudioClip> clips = new Dictionary<string, AudioClip>();
    private static readonly Dictionary<string, float> lastPlayed = new Dictionary<string, float>();

    private AudioSource source;

    /// <summary>Playing count for tests/diagnostics.</summary>
    public static int PlayedCount { get; private set; }

    private static GameAudio Instance
    {
        get
        {
            if (instance == null)
            {
                var go = new GameObject("GameAudio");
                DontDestroyOnLoad(go);
                go.hideFlags = HideFlags.HideAndDontSave;
                instance = go.AddComponent<GameAudio>();
                instance.source = go.AddComponent<AudioSource>();
                instance.source.playOnAwake = false;
                instance.source.spatialBlend = 0f;
            }
            return instance;
        }
    }

    /// <summary>Applies the saved master volume; call once when a scene starts.</summary>
    public static void ApplySavedVolume()
    {
        var data = PlayerHandleData.LoadOrDefault();
        AudioListener.volume = Mathf.Clamp01(data.masterVolume);
    }

    /// <summary>The volume steps the in-game speaker button cycles through.</summary>
    public static float NextVolume(float current)
    {
        if (current > 0.75f) return 0.5f;
        if (current > 0.25f) return 0f;
        return 1f;
    }

    /// <summary>Plays a clip by file name. minGap throttles rapid repeats (e.g. the eat blip).</summary>
    public static void Play(string name, float volume = 1f, float pitchJitter = 0.06f, float minGap = 0f)
    {
        if (AudioListener.volume <= 0.001f)
        {
            return;
        }

        float now = Time.unscaledTime;
        float last;
        if (minGap > 0f && lastPlayed.TryGetValue(name, out last) && now - last < minGap)
        {
            return;
        }
        lastPlayed[name] = now;

        AudioClip clip;
        if (!clips.TryGetValue(name, out clip))
        {
            clip = Resources.Load<AudioClip>("Audio/" + name);
            clips[name] = clip;
        }
        if (clip == null)
        {
            return;
        }

        var src = Instance.source;
        src.pitch = 1f + Random.Range(-pitchJitter, pitchJitter);
        src.PlayOneShot(clip, volume);
        PlayedCount++;
    }
}
